#!/bin/bash
 
# Get location of script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Add VSCREEN to the path
export PATH=$PATH:/cadtools5/vscreen/bin

# Run the controller using draw.txt
$SCRIPT_DIR/controller < $SCRIPT_DIR/draw.txt
